vim.filetype.add({
  extension = {
    conf = 'conf',
    template = 'html',
    mc = 'monkeyc',
    jxa = 'javascript',
  },
  filename = {
    ['Vagrantfile'] = 'ruby',
    ['.eslintrc'] = 'json',
    ['Brewfile'] = 'ruby',
    ['Dockerfile.*'] = 'dockerfile',
    ['.parcelrc'] = 'json',
    ['.terserrc'] = 'json',
    ['.stylelintrc'] = 'json',
    ['api-extractor.json'] = 'jsonc',
    ['docker-compose.yml'] = 'yaml.docker-compose',
    ['docker-compose.yaml'] = 'yaml.docker-compose',
    ['compose.yml'] = 'yaml.docker-compose',
    ['compose.yaml'] = 'yaml.docker-compose',
  },
  pattern = {
    ['~/.ssh/config.*'] = 'sshconfig',
    ['~/.config/git/hooks/.*'] = 'sh',
    ['~/.config/git/.*'] = 'gitconfig',
    ['~/.config/direnv/direnvrc'] = 'sh',
    ['~/.direnvrc'] = 'sh',
    ['~/.config/kitty/.*.conf'] = 'kitty',
    ['docker%-compose%..*%.ya?ml'] = 'yaml.docker-compose',
  },
})
