require('config.clipboard')
require('config.conceal')
require('config.misc')
require('config.diagnostics')
require('config.keymap')
require('config.commands')
require('config.quickfix')
require('config.lazy')
