-- Plugins managed by vim.pack, in dependency order.
-- Generated from the lazy.nvim specs; edit by hand from here on.

return {
  { src = 'https://github.com/L3MON4D3/LuaSnip' },
  { src = 'https://github.com/hrsh7th/cmp-nvim-lsp' },
  { src = 'https://github.com/hrsh7th/cmp-nvim-lua' },
  { src = 'https://github.com/hrsh7th/cmp-path' },
  { src = 'https://github.com/saadparwaiz1/cmp_luasnip' },
  { src = 'https://github.com/zbirenbaum/copilot.lua' },
  { src = 'https://github.com/dlyongemallo/diffview.nvim' },
  { src = 'https://github.com/lewis6991/gitsigns.nvim' },
  { src = 'https://github.com/neovim/nvim-lspconfig' },
  { src = 'https://github.com/josa42/nvim-telescope-config' },
  { src = 'https://github.com/nvim-lua/plenary.nvim' },
  { src = 'https://github.com/josa42/nvim-telescope-minimal-layout' },
  { src = 'https://github.com/nvim-telescope/telescope-fzf-native.nvim' },
  { src = 'https://github.com/nvim-telescope/telescope-ui-select.nvim' },
  { src = 'https://github.com/josa42/nvim-telescope-mask' },
  { src = 'https://github.com/itchyny/vim-gitbranch' },
  { src = 'https://github.com/josa42/nvim-telescope-workspaces' },
  { src = 'https://github.com/nvim-telescope/telescope.nvim' },
  { src = 'https://github.com/myakove/homeassistant-nvim' },
  { src = 'https://github.com/folke/lazydev.nvim' },
  { src = 'https://github.com/selimacerbas/live-server.nvim' },
  { src = 'https://github.com/arkav/lualine-lsp-progress' },
  { src = 'https://github.com/nvim-lualine/lualine.nvim' },
  { src = 'https://github.com/selimacerbas/markdown-preview.nvim' },
  { src = 'https://github.com/mason-org/mason-lspconfig.nvim' },
  { src = 'https://github.com/RubixDev/mason-update-all' },
  { src = 'https://github.com/mason-org/mason.nvim' },
  { src = 'https://github.com/timantipov/md-table-tidy.nvim' },
  { src = 'https://github.com/echasnovski/mini.nvim' },
  { src = 'https://github.com/nvimtools/none-ls.nvim' },
  { src = 'https://github.com/josa42/nvim-actions' },
  { src = 'https://github.com/windwp/nvim-autopairs' },
  { src = 'https://github.com/hrsh7th/nvim-cmp' },
  { src = 'https://github.com/josa42/nvim-gx', version = 'main' },
  { src = 'https://github.com/josa42/nvim-lsp-autoformat' },
  { src = 'https://github.com/josa42/nvim-lsp-codelens' },
  { src = 'https://github.com/josa42/nvim-quickfix' },
  { src = 'https://github.com/chrisgrieser/nvim-rulebook' },
  { src = 'https://github.com/kylechui/nvim-surround' },
  { src = 'https://github.com/josa42/nvim-tabline' },
  { src = 'https://github.com/josa42/nvim-templates' },
  { src = 'https://github.com/nvim-treesitter/nvim-treesitter', version = 'main' },
  { src = 'https://github.com/windwp/nvim-ts-autotag' },
  { src = 'https://github.com/josa42/nvim-unicorn' },
  { src = 'https://github.com/belltoy/prom.vim' },
  { src = 'https://github.com/MeanderingProgrammer/render-markdown.nvim' },
  { src = 'https://github.com/b0o/schemastore.nvim' },
  { src = 'https://github.com/AndrewRadev/splitjoin.vim' },
  { src = 'https://github.com/AndrewRadev/switch.vim' },
  { src = 'https://github.com/axelvc/template-string.nvim' },
  { src = 'https://github.com/josa42/theme-theonedark', name = 'theonedark' },
  { src = 'https://github.com/folke/ts-comments.nvim' },
  { src = 'https://github.com/pmizio/typescript-tools.nvim' },
  { src = 'https://github.com/mityu/vim-applescript' },
  { src = 'https://github.com/antonk52/vim-browserslist' },
  { src = 'https://github.com/zhaozg/vim-diagram' },
  { src = 'https://github.com/tpope/vim-eunuch' },
  { src = 'https://github.com/fladson/vim-kitty' },
  { src = 'https://github.com/jxnblk/vim-mdx-js' },
  { src = 'https://github.com/josa42/vim-monkey-c' },
  { src = 'https://github.com/josa42/vim-npmrc' },
  { src = 'https://github.com/darfink/vim-plist' },
  { src = 'https://github.com/tpope/vim-repeat' },
  { src = 'https://github.com/rhysd/vim-syntax-codeowners' },
  { src = 'https://github.com/kana/vim-textobj-user' }, -- must precede its dependents
  { src = 'https://github.com/fvictorio/vim-textobj-backticks' },
  { src = 'https://github.com/kana/vim-textobj-entire' },
  { src = 'https://github.com/kana/vim-textobj-indent' },
  { src = 'https://github.com/kana/vim-textobj-line' },
  { src = 'https://github.com/sgur/vim-textobj-parameter' },
  { src = 'https://github.com/whatyouhide/vim-textobj-xmlattr' },
  { src = 'https://github.com/josa42/vim-trivyignore' },
  { src = 'https://github.com/lukas-reineke/virt-column.nvim' },
}
